import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Nochi's World"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-4xl md:text-5xl xl:text-6xl font-bold ">
          <span className="text-blue-900">Nochi</span>는 러시아어로{" "}
          <span className="text-blue-900">밤</span>을 의미합니다.🌙
        </h1>

        
      </main>
    </>
  );
}
